#!/usr/bin/env bash
# Reclaim local build disk WITHOUT touching git-tracked files.
#
# Why builds grow: cargo never garbage-collects stale artifacts, every
# integration test statically links the whole dependency tree, and each extra
# build profile (coverage, cross-compile) keeps its own full tree. So target/
# accumulates tens of GB over a long session even though a *fresh* build is much
# smaller.
#
# This script removes the REGENERABLE trees and keeps the host dev/release
# builds, so it reclaims space without forcing a cold rebuild:
#   - target/llvm-cov-target, target/llvm-cov   (coverage; only CI needs it)
#   - target/doc                                (rustdoc output)
#   - target/<triple>/                          (cross-compile targets)
#   - target/*/incremental                      (incremental caches)
#   - target/flycheck*                          (editor check builds)
#   - fuzz/target                               (fuzz build)
#
# For a DEEP reset that also purges the 30-60 GB of stale host artifacts in
# target/debug/deps, run `cargo clean` (or `make trim-deep`) — that frees the
# most but the next build is cold. Keeping CARGO_INCREMENTAL=0 (the default in
# this repo's Makefile targets) stops the incremental cache from re-growing.
#
# Usage:
#   scripts/trim-build.sh            # reclaim
#   scripts/trim-build.sh --dry-run  # show what would be removed

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

DRY_RUN=0
[[ "${1:-}" == "--dry-run" || "${1:-}" == "-n" ]] && DRY_RUN=1

_free_gb() { df -g /System/Volumes/Data 2>/dev/null | tail -1 | awk '{print $4}'; }
BEFORE="$(_free_gb 2>/dev/null || echo '?')"

remove() {
    local path="$1"
    [[ -e "$path" ]] || return 0
    local sz
    sz="$(du -sh "$path" 2>/dev/null | cut -f1)"
    if [[ "$DRY_RUN" -eq 1 ]]; then
        printf 'would remove  %-8s %s\n' "$sz" "$path"
        return 0
    fi
    rm -rf "$path"
    printf 'removed       %-8s %s\n' "$sz" "$path"
}

# 1) Coverage profile (regenerated by `cargo llvm-cov` / CI only).
remove target/llvm-cov-target
remove target/llvm-cov

# 2) Rendered docs (regenerated by `cargo doc`).
remove target/doc

# 3) Editor flycheck build dirs.
for d in target/flycheck*; do remove "$d"; done

# 4) Cross-compile target trees (host build is target/{debug,release,...}).
while IFS= read -r -d '' t; do remove "$t"; done \
    < <(find target -mindepth 1 -maxdepth 1 -type d -name '*-*-*-*' -print0 2>/dev/null)

# 5) Incremental compilation caches under every profile.
while IFS= read -r -d '' inc; do remove "$inc"; done \
    < <(find target -mindepth 2 -maxdepth 2 -type d -name incremental -print0 2>/dev/null)

# 6) Fuzz build tree.
remove fuzz/target

AFTER="$(_free_gb 2>/dev/null || echo '?')"
if [[ "$DRY_RUN" -eq 0 ]]; then
    printf '\n\033[1;32m== free disk: %s GB -> %s GB ==\033[0m\n' "$BEFORE" "$AFTER"
    printf 'For a deep reset of stale host artifacts (target/debug/deps), run: cargo clean\n'
fi
